name: 'Continuous Benchmark'
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    contents: write
    contents-reason: to <reason_here> # specify why contents is used.