name: "Action Check Typescript errors"
github-token:
  action-input:
    input: repo-token
    is-default: false
  permissions:
    pull-requests: write
    pull-requests-reason: to <reason_here> # specify why pull-requests is used.
    issues: write
    issues-reason: to <reason_here> # specify why issues is used.