name: "size-limit-release"
github-token:
  action-input:
    input: github_token
    is-default: false
  permissions:
    contents: write
    contents-reason: to <reason_here> # specify why contents is used.