name: 'Workflow Dispatch'
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    actions: read
    actions-reason: to list the workfows and get assets
    #Refrences: https://github.com/benc-uk/workflow-dispatch/blob/827565b908f387ffd483c84312273ae185c06c8a/src/main.ts#L51
    #Refrences: https://github.com/benc-uk/workflow-dispatch/blob/827565b908f387ffd483c84312273ae185c06c8a/src/main.ts#L38