name: 'Configure GitHub Pages'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    contents: write
    contents-reason: to <reason_here> # specify why contents is used.