name: "Issue Auto Labeling and Assigning"
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
    issues: write
    issues-reason: to <reason_here> # specify why issues is used.