name: 'Run analysis of OSSF Scorecard'
github-token:
  action-input:
    input: repo_token
    is-default: false
  permissions: 
    contents: read
    contents-reason: to list releases
    actions: read
    actions-reason: to check for publishing workflows
    checks: read
    checks-reason: to check for SAST tool in check runs
    statuses: read
    statuses-reason: to check for CI tests in PRs
    issues: read
    issues-reason: to check if repo is maintained
    pull-requests: read
    pull-requests-reason: to check if PRs are reviewed
outbound-endpoints:
  - fqdn: api.github.com
    port: 443
    reason: to call GitHub APIs
  - fqdn: bestpractices.coreinfrastructure.org
    port: 443
    reason:  to check CII best practices badge level
  - fqdn: api.osv.dev
    port: 443
    reason:  to check vulnerabilities in the OSV database
harden-action-link: https://app.stepsecurity.io/github/step-security/agent/actions/runs/1523253753
