name: 'Setup Python'
github-token:
  action-input:
    input: token
    is-default: true
  permissions: # Used to pull python distributions from python-versions.

outbound-endpoints:
  - fqdn: raw.githubusercontent.com
    port: 443
    reason: to get manifest file
  
  - fqdn: downloads.python.org
    port: 443
    reason: to download python interpreter
  


