name: Add & Commit
github-token:
  action-input:
    input: github_token
    is-default: true
  permissions:
    contents: write
    contents-reason: to push changes to repo
    contents-if: ${{ with['push'] != 'false'}}
    

#Reference : https://github.com/EndBug/add-and-commit/blob/0e4f5f64171dcc332288834e2928909b389a9a8c/src/io.ts
