name: "Jekyll Deploy Action"
github-token : 
    action-input:
      input: token
      is-default: false
    permissions:
      contents: write
      contents-reason:  to deploy Jekyll site to github pages

#Reference - https://github.com/jeffreytse/jekyll-deploy-action/blob/7ca462647387e928a2af6e3fc48ed683b2719beb/README.md
