name: Contributors List
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: false
  permissions:
    contents: read
    contents-reason: to <reason_here> # specify why contents is used.