name: 'Repo Visualizer'
github-token:
  action-input:
    input: github_token
    is-default: true
  permissions:
    contents: write
    contents-if: {{!contains(with, 'should_push') || with['should_push'] == 'true'}}
    contents-reason: to read repo directories
    #Reference: https://github.com/githubocto/repo-visualizer/commit/a71a1e869c0848832eb983924dd80e6ca4de5880
outbound-endpoints:
  - fqdn: github.com
    port: 443
    reason: to fetch contents and push diagrams

harden-runner-link: https://app.stepsecurity.io/github/jauderho/sandbox/actions/runs/1734928151
