name: Release Commenter
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: false
  permissions:
    issues: write
    issues-reason: to <reason_here> # specify why issues is used.
    contents: read
    contents-reason: to <reason_here> # specify why contents is used.