name: Automate PR
on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  Automate:
    if: github.event.label.name == 'Automate'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: step-security/secure-workflows
    
      - name: Automate PR
        uses: step-security/secure-workflows/Automate-PR@ee3b1ddff60bd7fee0bf3c21a658c4c5f88c370b
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}