name: KBAnalysis
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
        with:
          repository: step-security/secure-workflows

      - name: KBAnalysis
        uses: step-security/secure-workflows/kbanalysis@8d6043e1e5071d26a93ab9ed5bc60d553f811092
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}

      - id: get-action
        uses: actions/github-script@5d03ada4b0a753e9460b312e61cc4f8fdeacf163
        with:
          script: |
            var id = "${{github.event.issue.title}}".split(' ')[6]
            core.setOutput('id', id)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672
        with:
          token: ${{secrets.PAT}} #  need to use PAT since GITHUB_TOKEN does not initiate workflows
          body: "This PR adds a YAML file to describe token permissions needed for Action: ${{steps.get-action.outputs.id}}."
          commit-message: "added KB for issue#${{github.event.issue.number}}"
          title: "[KB] Add GitHub token permissions for ${{steps.get-action.outputs.id}} Action"
          branch: "issue#${{github.event.issue.number}}"
