name: Test
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
        with:
          allowed-endpoints: api.github.com:443
            codecov.io:443
            uploader.codecov.io:443
            github.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - name: Set up Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: 1.15
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
        env:
          PAT: ${{ secrets.PAT }}
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
